In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('health.csv')
df

,State_Name,State_District_Name,AA_Sample_Units_Total,AA_Sample_Units_Rural,AA_Sample_Units_Urban,AA_Households_Total,AA_Households_Rural,AA_Households_Urban,AA_Population_Total,AA_Population_Rural,...,ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Lower_Limit,ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Upper_Limit,ZZ_Under_Five_Mortality_Rate_U5MR_Urban_Lower_Limit,ZZ_Under_Five_Mortality_Rate_U5MR_Urban_Upper_Limit,ZZ_Sex_Ratio_At_Birth_Total_Lower_Limit,ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit,ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit,ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit,ZZ_Sex_Ratio_At_Birth_Urban_Lower_Limit,ZZ_Sex_Ratio_At_Birth_Urban_Upper_Limit
0,Assam,Barpeta,53,47,6,13711,12765,946,64606,60293,...,54,70,NaN,NaN,871,985,851,965,908.0,1611.0
1,Assam,Bongaigaon,89,73,16,17384,14904,2480,84012,73899,...,58,73,NaN,NaN,897,1005,911,1026,621.0,956.0
2,Assam,Cachar,105,84,21,27488,24207,3281,127158,112171,...,68,80,31.0,57.0,891,966,871,949,905.0,1168.0
3,Assam,Darrang,26,24,2,5951,5769,182,29048,28256,...,79,107,NaN,NaN,913,1102,908,1097,NaN,NaN
4,Assam,Dhemaji,121,108,13,14481,12619,1862,75451,66537,...,40,53,11.0,38.0,935,1045,938,1054,772.0,1083.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,Uttarakhand,Pithoragarh,161,136,25,25265,20467,4798,102999,84627,...,24,34,NaN,NaN,724,813,734,833,581.0,798.0
280,Uttarakhand,Rudraprayag,225,222,3,33117,32914,203,139025,138266,...,23,30,NaN,NaN,817,898,816,897,NaN,NaN
281,Uttarakhand,Tehri Garhwal,351,317,34,47792,42354,5438,205575,181918,...,64,74,22.0,43.0,840,900,855,918,667.0,842.0
282,Uttarakhand,Udham Singh Nagar,81,45,36,17887,12393,5494,91518,64614,...,40,54,26.0,46.0,821,920,855,978,710.0,879.0
283,Uttarakhand,Uttarkashi,98,89,9,17945,15683,2262,76648,67984,...,46,61,14.0,55.0,850,972,862,991,610.0,989.0

In [3]:
print("checking for null values")
print(df.isnull().sum())

checking for null values
State_Name                                 0
State_District_Name                        0
AA_Sample_Units_Total                      0
AA_Sample_Units_Rural                      0
AA_Sample_Units_Urban                      0
                                          ..
ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit    0
ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit    0
ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit    0
ZZ_Sex_Ratio_At_Birth_Urban_Lower_Limit    9
ZZ_Sex_Ratio_At_Birth_Urban_Upper_Limit    9
Length: 644, dtype: int64

In [4]:
# count null values in each column
null_cols = df.isnull().sum()

# drop null columns
df = df.drop(columns=null_cols[null_cols > 0].index)

print(df)

      State_Name State_District_Name  AA_Sample_Units_Total  \
0          Assam             Barpeta                     53
1          Assam          Bongaigaon                     89
2          Assam              Cachar                    105
3          Assam             Darrang                     26
4          Assam             Dhemaji                    121
..           ...                 ...                    ...
279  Uttarakhand         Pithoragarh                    161
280  Uttarakhand         Rudraprayag                    225
281  Uttarakhand       Tehri Garhwal                    351
282  Uttarakhand   Udham Singh Nagar                     81
283  Uttarakhand          Uttarkashi                     98

     AA_Sample_Units_Rural  AA_Sample_Units_Urban  AA_Households_Total  \
0                       47                      6                13711
1                       73                     16                17384
2                       84                     21                27488
3                       24                      2                 5951
4                      108                     13                14481
..                     ...                    ...                  ...
279                    136                     25                25265
280                    222                      3                33117
281                    317                     34                47792
282                     45                     36                17887
283                     89                      9                17945

     AA_Households_Rural  AA_Households_Urban  AA_Population_Total  \
0                  12765                  946                64606
1                  14904                 2480                84012
2                  24207                 3281               127158
3                   5769                  182                29048
4                  12619                 1862                75451
..                   ...                  ...                  ...
279                20467                 4798               102999
280                32914                  203               139025
281                42354                 5438               205575
282                12393                 5494                91518
283                15683                 2262                76648

     AA_Population_Rural  ...  ZZ_Infant_Mortality_Rate_Rural_Lower_Limit  \
0                  60293  ...                                       36.00
1                  73899  ...                                       42.00
2                 112171  ...                                       50.00
3                  28256  ...                                       52.00
4                  66537  ...                                       31.00
..                   ...  ...                                         ...
279                84627  ...                                       20.19
280               138266  ...                                       16.72
281               181918  ...                                       51.84
282                64614  ...                                       32.57
283                67984  ...                                       34.64

     ZZ_Infant_Mortality_Rate_Rural_Upper_Limit  \
0                                         54.00
1                                         59.00
2                                         62.00
3                                         91.00
4                                         45.00
..                                          ...
279                                       29.69
280                                       21.99
281                                       60.79
282                                       49.03
283                                       50.99

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Lower_Limit  \
0                                                   51
1                                                   54
2                                                   64
3                                                   78
4                                                   39
..                                                 ...
279                                                 22
280                                                 23
281                                                 60
282                                                 38
283                                                 44

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Upper_Limit  \
0                                                   66
1                                                   68
2                                                   74
3                                                  105
4                                                   51
..                                                 ...
279                                                 31
280                                                 30
281                                                 69
282                                                 49
283                                                 59

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Lower_Limit  \
0                                                   54
1                                                   58
2                                                   68
3                                                   79
4                                                   40
..                                                 ...
279                                                 24
280                                                 23
281                                                 64
282                                                 40
283                                                 46

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Upper_Limit  \
0                                                   70
1                                                   73
2                                                   80
3                                                  107
4                                                   53
..                                                 ...
279                                                 34
280                                                 30
281                                                 74
282                                                 54
283                                                 61

     ZZ_Sex_Ratio_At_Birth_Total_Lower_Limit  \
0                                        871
1                                        897
2                                        891
3                                        913
4                                        935
..                                       ...
279                                      724
280                                      817
281                                      840
282                                      821
283                                      850

     ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit  \
0                                        985
1                                       1005
2                                        966
3                                       1102
4                                       1045
..                                       ...
279                                      813
280                                      898
281                                      900
282                                      920
283                                      972

     ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit  \
0                                        851
1                                        911
2                                        871
3                                        908
4                                        938
..                                       ...
279                                      734
280                                      816
281                                      855
282                                      855
283                                      862

     ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit
0                                        965
1                                       1026
2                                        949
3                                       1097
4                                       1054
..                                       ...
279                                      833
280                                      897
281                                      918
282                                      978
283                                      991

[284 rows x 445 columns]

In [5]:
# count null values in each column
null_cols = df.isnull().sum()

# display null columns and their count
null_cols = null_cols[null_cols > 0] # select columns with null values
print("Null values in columns:")
print(null_cols)

print("checking for null values")
print(df.isnull().sum())

Null values in columns:
Series([], dtype: int64)
checking for null values
State_Name                                             0
State_District_Name                                    0
AA_Sample_Units_Total                                  0
AA_Sample_Units_Rural                                  0
AA_Sample_Units_Urban                                  0
                                                      ..
ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Upper_Limit    0
ZZ_Sex_Ratio_At_Birth_Total_Lower_Limit                0
ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit                0
ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit                0
ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit                0
Length: 445, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284 entries, 0 to 283
Columns: 445 entries, State_Name to ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit
dtypes: float64(415), int64(28), object(2)
memory usage: 987.5+ KB

In [9]:
#creating train and test sets
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.25, random_state=531)
print(len(train_set), len(test_set))
print(train_set.head())
print(test_set.head())

213 71
         State_Name State_District_Name  AA_Sample_Units_Total  \
107  Madhya Pradesh                Guna                     33
167          Odisha             Sonapur                     73
165          Odisha            Rayagada                     54
21            Assam            Sonitpur                    138
14            Assam           Kokrajhar                     25

     AA_Sample_Units_Rural  AA_Sample_Units_Urban  AA_Households_Total  \
107                     23                     10                 5679
167                     65                      8                14937
165                     43                     11                 9370
21                     117                     21                30255
14                      22                      3                 3944

     AA_Households_Rural  AA_Households_Urban  AA_Population_Total  \
107                 3721                 1958                29399
167                13937                 1000                59949
165                 7481                 1889                35464
21                 27338                 2917               143695
14                  3553                  391                19029

     AA_Population_Rural  ...  ZZ_Infant_Mortality_Rate_Rural_Lower_Limit  \
107                19421  ...                                        61.0
167                56001  ...                                        42.0
165                28164  ...                                        48.0
21                131125  ...                                        53.0
14                 17284  ...                                        52.0

     ZZ_Infant_Mortality_Rate_Rural_Upper_Limit  \
107                                      100.55
167                                       57.00
165                                       74.00
21                                        75.00
14                                       104.00

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Lower_Limit  \
107                                                 82
167                                                 68
165                                                 86
21                                                  67
14                                                  84

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Upper_Limit  \
107                                                105
167                                                 86
165                                                111
21                                                  79
14                                                 117

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Lower_Limit  \
107                                                 89
167                                                 69
165                                                 91
21                                                  71
14                                                  89

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Upper_Limit  \
107                                                118
167                                                 87
165                                                119
21                                                  83
14                                                 125

     ZZ_Sex_Ratio_At_Birth_Total_Lower_Limit  \
107                                      788
167                                      864
165                                      828
21                                       916
14                                       798

     ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit  \
107                                      930
167                                      986
165                                      979
21                                      1000
14                                       996

     ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit  \
107                                      797
167                                      868
165                                      819
21                                       910
14                                       791

     ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit
107                                      967
167                                      995
165                                      986
21                                       998
14                                       997

[5 rows x 445 columns]
        State_Name State_District_Name  AA_Sample_Units_Total  \
166         Odisha           Sambalpur                     60
212  Uttar Pradesh           Barabanki                     46
25           Bihar               Banka                     68
33           Bihar               Jamui                     43
0            Assam             Barpeta                     53

     AA_Sample_Units_Rural  AA_Sample_Units_Urban  AA_Households_Total  \
166                     38                     22                11348
212                     39                      7                11232
25                      63                      5                16677
33                      38                      5                 9045
0                       47                      6                13711

     AA_Households_Rural  AA_Households_Urban  AA_Population_Total  \
166                 6995                 4353                47946
212                10594                  638                58722
25                 16131                  546                81445
33                  8597                  448                49514
0                  12765                  946                64606

     AA_Population_Rural  ...  ZZ_Infant_Mortality_Rate_Rural_Lower_Limit  \
166                28801  ...                                       45.00
212                54961  ...                                       57.06
25                 78689  ...                                       37.00
33                 46921  ...                                       40.00
0                  60293  ...                                       36.00

     ZZ_Infant_Mortality_Rate_Rural_Upper_Limit  \
166                                       72.00
212                                       82.37
25                                        50.00
33                                        61.00
0                                         54.00

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Lower_Limit  \
166                                                 52
212                                                 88
25                                                  52
33                                                  61
0                                                   51

     ZZ_Under_Five_Mortality_Rate_U5MR_Total_Upper_Limit  \
166                                                 71
212                                                105
25                                                  63
33                                                  77
0                                                   66

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Lower_Limit  \
166                                                 64
212                                                 91
25                                                  51
33                                                  62
0                                                   54

     ZZ_Under_Five_Mortality_Rate_U5MR_Rural_Upper_Limit  \
166                                                 90
212                                                109
25                                                  63
33                                                  78
0                                                   70

     ZZ_Sex_Ratio_At_Birth_Total_Lower_Limit  \
166                                      823
212                                      873
25                                       940
33                                       916
0                                        871

     ZZ_Sex_Ratio_At_Birth_Total_Upper_Limit  \
166                                      960
212                                      983
25                                      1040
33                                      1041
0                                        985

     ZZ_Sex_Ratio_At_Birth_Rural_Lower_Limit  \
166                                      797
212                                      876
25                                       944
33                                       921
0                                        851

     ZZ_Sex_Ratio_At_Birth_Rural_Upper_Limit
166                                      972
212                                      991
25                                      1046
33                                      1050
0                                        965

[5 rows x 445 columns]

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier

x=df[['XX_Women_Who_Are_Aware_Of_Danger_Signs_Of_Ari_Pneumonia_Total','YY_Crude_Death_Rate_Cdr_Total_Person','MM_Pregnancy_To_Women_Aged_15_49_Years_Resulting_In_Abortion_Total']]
y=df['AA_Population_Total']

lin_reg = LinearRegression()
print(lin_reg.fit(x, y))
print("Linear Regression accuracy: ", (lin_reg.score(x,y))*100)

Rndm_modl = RandomForestClassifier()
Rndm_modl.fit(x,y)
print("Random Forest accuracy: ", (Rndm_modl.score(x,y))*100)

decs_modl = DecisionTreeClassifier()
decs_modl.fit(x,y)
print("Decision Tree Classifier accuracy: ", (decs_modl.score(x,y))*100)

svm_modl = SVC()
svm_modl.fit(x,y)
print("SVM accuracy: ", (svm_modl.score(x,y))*100)

LinearRegression()
Linear Regression accuracy:  8.546469322816863
Random Forest accuracy:  100.0
Decision Tree Classifier accuracy:  100.0
SVM accuracy:  100.0